import {  Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});



export const metadata = {
  title: "Bus-Ticket-Landing-Page-with-next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-raleway">
        <Navbar />
        {children}
      </body>
    </html>
  );
}